### ISSUE TITLE
Strange plot points on curves from SVG conversion 

### ISSUE THREAD

**Issue by Milner99** [sameer/svg2gcode#18]
[happy dog svg and gcode.zip](https://github.com/sameer/svg2gcode/files/7100766/happy.dog.svg.and.gcode.zip)

Hi,

Attached is an SVG and GCode output from the online demo of svg2gcode. Seeing some strange plotted points near the head of the cartoon dog. Is this something going on in the SVG or the conversion?

Would love some advise and guidance please. thank you so much
Chris.

**Comment by sameer** [comment]
Hi Chris,

Thank you for bringing this to my attention. Just pushed changes that fix the strange plot points:

![g-code for Chris's image plotted showing that it is now correct](https://user-images.githubusercontent.com/11097096/131904137-19ed331a-749d-4f03-8cc3-a35c4cd0baeb.png)

This was a miss on my part when refactoring svg2gcode to support circular interpolation.

* Root cause: incorrect multiplication in control point tracking
* Action taken: 
    * Correct the issue and push changes for that
    * Add test cases using the provided image to ensure this particular use case does not see future regressions
    * Making plans to test other edge cases based on coverage reports

**Comment by sameer** [comment]
I have confirmed that those changes have reached the web interface.

Thank you for using svg2gcode! Please let me know if you run into any other problems :slightly_smiling_face:

**Comment by Milner99** [comment]
Wow, quick work. Thank you so much!
